version: "3.7"
services:
    nest:
        build: .docker/Dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./app:/usr/src/app
        command: bash -c "tail -f /dev/null"
